image: python:3.8.10

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip3 install -r requirements.txt
  - pip3 install -e .

build-job:
  stage: build
  script:
    - echo "Build success"

check-job:
  stage: test
  script:
    - apt update
    - apt install --assume-yes mosquitto
    - service mosquitto start
    - pip3 install pytest
    - pip3 install coverage
    - coverage run --source ./mango -m pytest
    - coverage report

pylint-job:
  stage: test
  script:         
    - pip3 install pylint
    - pylint mango
  allow_failure: 
    exit_codes: 
      - 1

upload-job:
  stage: deploy
  variables:
    TWINE_USERNAME: $TWINE_USERNAME
    TWINE_PASSWORD: $TWINE_PASSWORD
  only:
    - tags
  except:
    - branches
  script:
    - pip3 install twine
    - python setup.py sdist bdist_wheel
    - twine check dist/*
    - twine upload dist/* -u $TWINE_USERNAME -p $TWINE_PASSWORD




